export const GET_USERS = 'GET_USERS';
export const SUCCESS_GET_USERS = 'SUCCESS_GET_USERS';
export const ERROR_GET_USERS = 'ERROR_GET_USERS';

export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const SUCCESS_GET_USER_BY_ID = 'SUCCESS_GET_USER_BY_ID';
export const ERROR_GET_USER_BY_ID = 'ERROR_GET_USER_BY_ID';
